[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow     = "1.0.89"
basic-toml = "0.1.9"
chrono     = "0.4.38"
clap       = { version = "4.5.19",  features = ["derive"] }
csv        = "1.3.0"
env_logger = "0.11.5"
log        = "0.4.22"
minijinja  = "2.3.1"
semver     = { version = "1.0.23",  features = ["serde"] }
serde      = { version = "1.0.210", features = ["derive"] }
strum      = { version = "0.26.3",  features = ["derive"] }
toml_edit  = "0.22.22"
esp-metadata = { path = "../esp-metadata", features = ["clap"] }
