[target.riscv32imac-unknown-none-elf]
# runner = "espflash flash --monitor"
runner = "probe-rs run --chip esp32c6 --always-print-stacktrace"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[build]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = [ "core" ]
